<<<<<<< HEAD
import { Header } from '@/components/header'
import { Saira } from 'next/font/google'
import './globals.css'
=======
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
>>>>>>> 72bcd24ea19e3ec97fc4f106fd793e832a051078

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

<<<<<<< HEAD
const saira = Saira({
  weight:['300', '400', '500', '600'],
  subsets: ['latin'],
})

=======
>>>>>>> 72bcd24ea19e3ec97fc4f106fd793e832a051078
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={saira.className}></body>
      <Header/>
      {children}
=======
      <body className={inter.className}>{children}</body>
>>>>>>> 72bcd24ea19e3ec97fc4f106fd793e832a051078
    </html>
  )
}
