import { Header } from '@/components/header'
import { Saira } from 'next/font/google'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const saira = Saira({
  weight:['300', '400', '500', '600'],
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={saira.className}></body>
      <Header/>
      {children}
    </html>
  )
}
